export const mainnetChains = [
  {
    name: "Rizon",
    registryName: "rizon",
    valoper: "rizonvaloper1h7qgg8p52vdpcqzhxrt6wjsnyyfasaak588lrh",
    coinId: "rizon",
    exponent: 6,
  },
  {
    name: "KiChain",
    registryName: "kichain",
    valoper: "kivaloper1ggrrt80qln07kqnfe5zppjgsrrqmkc4jpwvsgh",
    coinId: "ki",
    exponent: 6,
  },
  {
    name: "BitCanna",
    registryName: "bitcanna",
    valoper: "bcnavaloper19l7slf3853c9ul0vf24zefjvdq4l8930nulqp4",
    coinId: "bitcanna",
    exponent: 6,
  },
  {
    name: "SifChain",
    registryName: "sifchain",
    valoper: "sifvaloper1tvy5apxqsf3jf0uhzknvj6qndy473smzjezvh9",
    coinId: "sifchain",
    exponent: 18,
  },
  {
    name: "FirmaChain",
    registryName: "firmachain",
    valoper: "firmavaloper1rkcxlv6t6tygmfnnp3v270qru3uq0lnxpatjst",
    coinId: "firmachain",
    exponent: 6,
  },
  {
    name: "Galaxy",
    registryName: "galaxy",
    valoper: "galaxyvaloper173mgkdad6f935ys7gd2yfj6z47khkwy6f9ce7n",
    exponent: 6,
    apr: 156,
  },
  {
    name: "Chronic",
    registryName: "chronicnetwork",
    valoper: "chronicvaloper1rwyn6w46u3067enhpdceqasg2um8dddtp9v3kx",
    exponent: 6,
  },
  {
    name: "Kujira",
    registryName: "kujira",
    valoper: "kujiravaloper1yafsywsluqdvlhtp30tcdhw496vg6ey3zs4u84",
    coinId: "kujira",
    exponent: 6,
  },
  {
    name: "Passage",
    registryName: "passage",
    valoper: "pasgvaloper1xp70wy9t4cqal2guacy7n8tmjf7avz8yz95kpn",
    exponent: 6,
  },
  // {
  //   name: "Mises",
  //   valoper: "",
  //   registryName: "",
  //   stakeLink: "https://gw.mises.site/validators",
  // },
]
